[[main]]
name = "Start"
url = "/de/"
weight = 10

[[main]]
identifier = "services"
name = "Services"
url = "#"
weight = 20

[[main]]
name = "Ideologie"
url = "/de/ideologie.html"
weight = 30

[[main]]
name = "Blog"
url = "/blog/"
weight = 40

[[main]]
name = "Manual"
url = "https://www.blunix.com/manual/"
weight = 50

[[main]]
name = "Code"
url = "https://git.blunix.com/welcome/index.html"
weight = 60

[[main]]
name = "Jobs"
url = "/de/jobs.html"
weight = 70

[[main]]
name = "Kontakt"
url = "/de/index.html#contact"
weight = 80

[[footer]]
identifier = "website"
name = "Website"
url = "#"
weight = 10

[[footer]]
parent = "website"
name = "Startseite"
url = "/de/"
weight = 10

[[footer]]
parent = "website"
name = "Linux Support"
url = "/de/linux-support.html"
weight = 20

[[footer]]
parent = "website"
name = "Linux Consulting"
url = "/de/linux-consulting.html"
weight = 30

[[footer]]
parent = "website"
name = "Managed Hosting"
url = "/de/linux-managed-hosting.html"
weight = 40

[[footer]]
parent = "website"
name = "Qubes OS Beratung und Support"
url = "/de/qubes-os-beratung-und-support.html"
weight = 50

[[footer]]
parent = "website"
name = "Schulungen"
url = "/de/linux-schulungen-und-workshops.html"
weight = 60

[[footer]]
parent = "website"
name = "Ideologie"
url = "/de/ideologie.html"
weight = 70

[[footer]]
parent = "website"
name = "Jobs"
url = "/de/jobs.html"
weight = 80

[[footer]]
parent = "website"
name = "Kontakt"
url = "/de/#contact"
weight = 85

[[footer]]
parent = "website"
name = "Datenschutz und Rechtliches"
url = "/de/rechtliches-und-datenschutz.html"
weight = 90

[[footer]]
identifier = "hosting"
name = "Hosting"
url = "#"
weight = 20

[[footer]]
parent = "hosting"
name = "Dokumentation"
url = "https://www.blunix.com/manual/"
weight = 10

[[footer]]
parent = "hosting"
name = "Code"
url = "https://git.blunix.com/welcome/index.html"
weight = 20

[[footer]]
parent = "hosting"
name = "Blog"
url = "/blog/"
weight = 30

[[services]]
name = "Linux Notfall Support"
url = "/de/linux-notfall-support.html"
weight = 10
[services.params]
icon = "uil uil-fire"

[[services]]
name = "Linux Support"
url = "/de/linux-support.html"
weight = 20
[services.params]
icon = "uil uil-fire"

[[services]]
name = "Linux Beratung f√ºr Projekte"
url = "/de/linux-consulting.html"
weight = 30
[services.params]
icon = "uil uil-server"
extraSpacing = true

[[services]]
name = "Linux Managed Hosting"
url = "/de/linux-managed-hosting.html"
weight = 40
[services.params]
icon = "uil uil-cloud-data-connection"

[[services]]
name = "Qubes OS Consulting"
url = "/de/qubes-os-beratung-und-support.html"
weight = 50
[services.params]
icon = "uil uil-window-grid"

[[services]]
name = "Schulungen & Workshops"
url = "/de/linux-schulungen-und-workshops.html"
weight = 60
[services.params]
icon = "uil uil-graduation-cap"
