[[main]]
name = "Startseite"
url = "/de/index.html"
weight = 10

[[main]]
identifier = "services"
name = "Services"
url = "#"
weight = 20

[[main]]
name = "Ideologie"
url = "/de/ideology.html"
weight = 30

[[main]]
name = "Blog"
url = "/blog/"
weight = 40

[[main]]
name = "Handbuch"
url = "https://www.blunix.com/manual/"
weight = 50

[[main]]
name = "Code"
url = "https://git.blunix.com/welcome/index.html"
weight = 60

[[main]]
name = "Jobs"
url = "/de/jobs.html"
weight = 70

[[main]]
name = "Kontakt"
url = "/de/index.html#contact"
weight = 80

[[footer]]
name = "Startseite"
url = "/de/index.html"
weight = 10

[[footer]]
name = "Linux Support"
url = "/de/linux-support.html"
weight = 20

[[footer]]
name = "Linux Consulting"
url = "/de/linux-consulting.html"
weight = 30

[[footer]]
name = "Managed Hosting"
url = "/de/linux-managed-hosting.html"
weight = 40

[[footer]]
name = "Qubes OS"
url = "/de/qubes-os-consulting-and-support.html"
weight = 50

[[footer]]
name = "Training"
url = "/de/linux-personal-trainings-and-workshops.html"
weight = 60

[[footer]]
name = "Ideologie"
url = "/de/ideology.html"
weight = 70

[[footer]]
name = "Jobs"
url = "/de/jobs.html"
weight = 80

[[footer]]
name = "Kontakt"
url = "/de/index.html#contact"
weight = 85

[[footer]]
name = "Rechtliches & Datenschutz"
url = "/de/legal-and-privacy.html"
weight = 90

[[services]]
name = "Linux Notfall Support"
url = "/de/linux-emergency-support.html"
weight = 10
[services.params]
icon = "uil uil-fire"

[[services]]
name = "Linux Support"
url = "/de/linux-support.html"
weight = 20
[services.params]
icon = "uil uil-fire"

[[services]]
name = "Linux Consulting"
url = "/de/linux-consulting.html"
weight = 30
[services.params]
icon = "uil uil-server"
extraSpacing = true

[[services]]
name = "Linux Managed Hosting"
url = "/de/linux-managed-hosting.html"
weight = 40
[services.params]
icon = "uil uil-cloud-data-connection"

[[services]]
name = "Qubes OS Beratung"
url = "/de/qubes-os-consulting-and-support.html"
weight = 50
[services.params]
icon = "uil uil-window-grid"

[[services]]
name = "Schulungen & Workshops"
url = "/de/linux-personal-trainings-and-workshops.html"
weight = 60
[services.params]
icon = "uil uil-graduation-cap"
