logo = '/images/logo.svg'

footer_logo = '/images/logo-full.svg'

featured_image = 'featured.webp'


[[contact]]
name = "info@blunix.com"
icon = "fa-solid fa-envelope"
link = "mailto:info@blunix.com"

[[contact]]
name = "+49 30 / 629 322 67"
icon = "fa-solid fa-phone"
link = "tel:+493062932267"


[[banner_link]]
name = "+49 30 / 629 322 67"
icon = "fa-solid fa-mobile-screen-button"
link = "tel:+493062932267"

[[banner_link]]
name = "info@blunix.com"
icon = "fa-solid fa-envelope"
link = "mailto:info@blunix.com"
